title: Natural Colour
author: TennenShoku
email: 
description: > # this means to ignore newlines until "baseurl:"
  A place for personal expression.

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  tennenshoku # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
